package PaulsGym.Panels;

import Defaults.Fonts;
import Defaults.Sizes;
import PaulsGym.MyButton;
import PaulsGym.MyLabel;
import PaulsGym.StartPanelActions;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.swing.SwingConstants.CENTER;

public class StartPanel extends javax.swing.JPanel {
    private StartPanelActions actions;
    
    public StartPanel(StartPanelActions actions) {
        
        this.actions = actions;
        initComponents();
        myInitComponents();
    }
    
    // My components 
    private void myInitComponents() {
        
        // Creates a label to welcome the user
        MyLabel welcomeLabel = new MyLabel("Welcome to Paul's Gym", Sizes.BIG_LABEL, new Point(350, 0), Fonts.HEADER);
        welcomeLabel.setHorizontalAlignment(CENTER);
        
        // Creates a button to enter the gym
        MyButton startButton = new MyButton(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actions.enterGym();
            }
        }, "Enter Gym", new Point(350, 400), Sizes.NORMAL_RECTANGLE_BUTTON, Fonts.NORMAL);
        
        // Adds the components to the panel
        this.add(welcomeLabel);
        this.add(startButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(Sizes.START_PANEL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
